{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n    \n    \n>       assert False\nE       assert False\n\ntest_alluredemo.py:12: AssertionError"}, "start": 1616899047637, "stop": 1616899047637, "uuid": "d89ef592-1112-4405-8657-96380aa9406a", "historyId": "e3535563f27e644c4a3371e45c952575", "testCaseId": "cdaed0cfb7279459338013af0d443b47", "fullName": "test_alluredemo#test_failure", "labels": [{"name": "suite", "value": "test_alluredemo"}, {"name": "host", "value": "SKY-20200805OYN"}, {"name": "thread", "value": "2164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alluredemo"}]}