{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <test_allure_story.TestLogin object at 0x000002105DCB1588>\n\n    @allure.story(\"密码缺失\")\n    def test_login_failure(self):\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print (\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失败\"):\n>           assert '1'==1\nE           AssertionError: assert '1' == 1\n\ntest_allure_story.py:27: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1616900591719, "stop": 1616900591719}, {"name": "点击密码", "status": "passed", "start": 1616900591719, "stop": 1616900591719}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"E:\\open_test\\test_allure_story.py\", line 27, in test_login_failure\n    assert '1'==1\n"}, "start": 1616900591719, "stop": 1616900591720}], "attachments": [{"name": "stdout", "source": "1cf59aca-3a6f-4429-989e-70a774c4d854-attachment.txt", "type": "text/plain"}], "start": 1616900591719, "stop": 1616900591720, "uuid": "ca969562-0ea5-41d7-89b4-55a6ba0c18cb", "historyId": "fbff15c07dd901d8fa492046e1d605b0", "testCaseId": "e09730822751dfbc16dda95738658248", "fullName": "test_allure_story.TestLogin#test_login_failure", "labels": [{"name": "story", "value": "密码缺失"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_allure_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "SKY-20200805OYN"}, {"name": "thread", "value": "10332-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure_story"}]}